### PR TITLE
Fixed some eslint warnings related to const/let

### LINKED ISSUE #208: Some questions about "prefer-const" rule warnings...
There are some warnings from ESLint rule "prefer-const" that I left unchanged because I wasn't sure how to fix them, I'd appreciate some help with them:

```
wampy.js/test/fake-ws-set-protocol.js
17:5  warning  'WebSocket' is never reassigned. Use 'const' instead prefer-const
41:5  warning  'setProtocol' is never reassigned. Use 'const' instead  prefer-const

wampy.js/test/fake-ws.js
30:5  warning  'WebSocket' is never reassigned. Use 'const' instead
 ```
1) Aren't WebSocket and setProtocol a `class WebSocket` and a `function setProtocol` declaration ? Is it safe to rewrite them like this instead of assigning them to a `let` ?

```
wampy.js/test/wampy-common-test.js
1844:21  warning  'reqId' is never reassigned. Use 'const' instead  prefer-const
1875:21  warning  'reqId' is never reassigned. Use 'const' instead  prefer-const
```
2) Here I'm a bit confused, I'm not too familiarized with this, but 'reqId' seems to be used before it is declared, as an argument of `wampy.cancel(reqId ...` is it supposed to be like this? Is it possible to rewrite it using `const` instead?

### PR DESCRIPTION
**Pull request by KSDaemon**
This fixes a few eslint warnings. 
Also closes #208 

### What kind of change does this PR introduce?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Refactoring (no new functionality, only code improvements)

### Checklist:

- [x] My code follows the code style of this project.
- [ ] I have added tests to cover my changes.
- [x] Overall test coverage is not decreased.
- [x] All new and existing tests passed.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: test/wampy-common-test.js [hunk 1]
```diff
@@ -1841,7 +1841,7 @@ serializers.forEach(function (item) {
             });
 
             it('checks options during canceling RPC invocation', function (done) {
-                let reqId;
+                let reqId;  // eslint-disable-line prefer-const
```
Comment (lucasrmendonca) [inline test/wampy-common-test.js:1844]: It seems the rule has a config option that already disables cases like this one:
https://eslint.org/docs/latest/rules/prefer-const#ignorereadbeforeassign

I would prefer setting this to true over adding this comment, what do you think?

Comment (KSDaemon) [reply test/wampy-common-test.js:1844]: Oh, Indeed! Agree! Setting is better then inline comment!
